# Fine-tuning Gemma2 2B model on Roadrunner with JAX, Flax.

We have adopted the Gemma2 notebook from Google Deepmind to use HuggingFace's libraries and and simplified the steps.

In [40]:
import kagglehub
import os
os.environ['KAGGLE_USERNAME'] = 'felarof99'
os.environ['KAGGLE_KEY'] = '1bf21523d3337386eac3aa5d61d62b7c'
kagglehub.login()

In [43]:
%%capture
weights_dir = path = kagglehub.model_download("google/gemma-2/flax/gemma2-2b-it")

In [44]:
weights_dir

'/root/.cache/kagglehub/models/google/gemma-2/flax/gemma2-2b-it/1'

In [45]:
from huggingface_hub import HfApi
api = HfApi()
api.upload_folder(
    folder_path=weights_dir,
    repo_id="felafax/gemma-2-2b-it-Flax",
    repo_type="model",
    ignore_patterns=[".*"],
    token=HUGGINGFACE_TOKEN
)

834bb4bf1e3854eb09f6208c95c071b2:   0%|          | 0.00/1.83G [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

bf69258061ae5f35eb7a5669fe6877d4:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Upload 3 LFS files:   0%|          | 0/3 [00:00<?, ?it/s]

CommitInfo(commit_url='https://huggingface.co/felafax/gemma-2-2b-it-Flax/commit/653a2d881e802c9f4a0af927a5d46116fb33ec25', commit_message='Upload folder using huggingface_hub', commit_description='', oid='653a2d881e802c9f4a0af927a5d46116fb33ec25', pr_url=None, pr_revision=None, pr_num=None)

## Setup

In [5]:
%%capture
!pip install --upgrade kagglehub -q
!pip install ipywidgets -q
!pip install tensorflow-cpu -q
!pip install tensorflow_datasets -q
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu -q
!pip install git+https://github.com/felafax/gemma.git -q

In [31]:
os.environ['HF_HUB_CACHE'] = '/mnt/persistent-disk/hf/'
os.environ['HF_HOME'] = '/mnt/persistent-disk/hf/'
!export HF_HUB_CACHE="/mnt/persistent-disk/hf/"
!export HF_HOME="/mnt/persistent-disk/hf/"

In [14]:
# HuggingFace username and token to use when uploading.
HUGGINGFACE_USERNAME = input("Please provide your HUGGINGFACE_USERNAME: ")
HUGGINGFACE_TOKEN = input("**INPUT** you huggingface token: ") # YOUR_HF_TOKEN

Please provide your HUGGINGFACE_USERNAME:  felafax
**INPUT** you huggingface token:  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


In [29]:
# @title Python imports

import enum
import re
import string

# We import JAX and some related packages.
import chex
import jax
import jax.numpy as jnp
import optax
from functools import partial

# We will use HuggingFace's dataset, tokenizer, and model classes.
from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer, default_data_collator
from datasets import Dataset, load_dataset, concatenate_datasets
import torch

# Finally, we import Gemma.
from gemma import params as params_lib
from gemma import sampler as sampler_lib
from gemma import transformer as transformer_lib
import sentencepiece as spm


In [30]:
# HuggingFace username and token to use when downloading.
MODEL_NAME="felafax/gemma-2-2b-it-Flax"
HUGGINGFACE_USERNAME = input("Please provide your HUGGINGFACE_USERNAME: ")
HUGGINGFACE_TOKEN = input("**INPUT** you huggingface token: ")

model_name=MODEL_NAME
hugging_face_token=HUGGINGFACE_TOKEN

In [49]:
from huggingface_hub import snapshot_download

ckpt_path = snapshot_download(repo_id=MODEL_NAME, token=HUGGINGFACE_TOKEN)
vocab_path = os.path.join(ckpt_path, 'tokenizer.model')

print(ckpt_path)
print()
print(vocab_path)

Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]

README.md:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

gemma2-2b-it/_CHECKPOINT_METADATA:   0%|          | 0.00/92.0 [00:00<?, ?B/s]

.gitattributes:   0%|          | 0.00/1.72k [00:00<?, ?B/s]

gemma2-2b-it/descriptor/descriptor.pbtxt:   0%|          | 0.00/45.0 [00:00<?, ?B/s]

gemma2-2b-it/checkpoint:   0%|          | 0.00/23.1k [00:00<?, ?B/s]

gemma2-2b-it/_METADATA:   0%|          | 0.00/56.7k [00:00<?, ?B/s]

(…)2b-it/d/b5a4695f4be0a2f41ec1e25616ebd7e7:   0%|          | 0.00/2.72k [00:00<?, ?B/s]

gemma2-2b-it/manifest.ocdbt:   0%|          | 0.00/118 [00:00<?, ?B/s]

(…)ess_0/d/fc20151969d7ca91ea9d8275bda0e219:   0%|          | 0.00/2.71k [00:00<?, ?B/s]

(…)ma2-2b-it/ocdbt.process_0/manifest.ocdbt:   0%|          | 0.00/180 [00:00<?, ?B/s]

834bb4bf1e3854eb09f6208c95c071b2:   0%|          | 0.00/1.83G [00:00<?, ?B/s]

bf69258061ae5f35eb7a5669fe6877d4:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

/root/.cache/huggingface/hub/models--felafax--gemma-2-2b-it-Flax/snapshots/653a2d881e802c9f4a0af927a5d46116fb33ec25

/root/.cache/huggingface/hub/models--felafax--gemma-2-2b-it-Flax/snapshots/653a2d881e802c9f4a0af927a5d46116fb33ec25/tokenizer.model


## Fine tuning the Gemma model

In [53]:
# Load parameters.
params = params_lib.load_and_format_params(os.path.join(ckpt_path, 'gemma2-2b-it'))

In [66]:
# Load model config.
config_2b = transformer_lib.TransformerConfig.gemma2_2b(cache_size=30)

# You can also infer the model config by using the number of layers in the params.
# config_2b = transformer_lib.TransformerConfig.from_params(params, cache_size=30)

In [62]:
model_2b = transformer_lib.Transformer(config=config_2b)

## Step 1: prepare the dataset

For this project, we're utilizing the refined **Alpaca dataset**, curated by yahma. This dataset is a carefully filtered selection of 52,000 entries from the original Alpaca collection. Feel free to substitute this section with your own data preparation code if you prefer.

It's crucial to include the EOS_TOKEN (End of Sequence Token) in your tokenized output. Failing to do so may result in endless generation loops.

In [67]:
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME, 
    token=HUGGINGFACE_TOKEN
)
if not tokenizer.pad_token:
    print("Tokenizer doesn't have a pad token.")
    tokenizer.pad_token = tokenizer.eos_token

tokenizer_config.json:   0%|          | 0.00/46.9k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/555 [00:00<?, ?B/s]

In [68]:
def get_dataset(*, tokenizer, batch_size=1, max_length=25, debug_mode=True):
    # Define Alpaca prompt template
    alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
    
    ### Instruction: {}
    
    ### Input: {}
    
    ### Response: {}"""
    
    EOS_TOKEN = tokenizer.eos_token
    
    # Define formatting function.
    def _format_prompts(examples):
        instructions = examples["instruction"]
        inputs = examples["input"]
        outputs = examples["output"]
        texts = []
        for instruction, input, output in zip(instructions, inputs, outputs):
            text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
            texts.append(text)
        return {"text": texts}

    def _tokenize(examples, max_length=None):
        tokenized = tokenizer(examples["text"], truncation=True, padding="max_length", max_length=25+1 if not max_length else max_length+1)
        tokenized['input_ids'] = [input_id[:-1] for input_id in tokenized['input_ids']]
        return {
            'input_tokens': tokenized['input_ids'],
            'target_mask': tokenized['attention_mask']
        }

    def _custom_collate_fn(batch):
        """Applies default_collate_fn from transformers and converts to JAX NumPy arrays."""
        batch = default_data_collator(batch)
        jax_batch = {}
        for key, value in batch.items():
            if isinstance(value, torch.Tensor):
                jax_batch[key] = jnp.array(value.numpy())
            else:
                jax_batch[key] = value
        
        return jax_batch

    # Load and preprocess the dataset.
    dataset = load_dataset("yahma/alpaca-cleaned", split="train")
    if debug_mode:
        dataset = dataset.select(range(32)) # Use just 32 exampfor faster iteration
    dataset = dataset.map(_format_prompts, batched=True)

    # Create train and test dataset.
    ds = dataset.train_test_split(test_size=0.15)
    ds['train'] = ds['train'].map(_tokenize, batched=True, remove_columns=dataset.column_names)
    ds['test'] = ds['test'].map(_tokenize, batched=True, remove_columns=dataset.column_names)

    # Create DataLoader
    train_dataloader = torch.utils.data.DataLoader(
        ds['train'],
        shuffle=True,
        batch_size=1 if not batch_size else batch_size,
        collate_fn=_custom_collate_fn
    )
    
    test_dataloader = torch.utils.data.DataLoader(
        ds['test'],
        shuffle=True,
        batch_size=1 if not batch_size else batch_size,
        collate_fn=_custom_collate_fn
    )

    return train_dataloader, test_dataloader

In [69]:
# # Test Dataset
train_dataloader, _ = get_dataset(tokenizer=tokenizer)
for i, batch in enumerate(train_dataloader):
    if i>10:
        break
    input_ids, attention_mask = (
        batch["input_tokens"],
        batch["target_mask"],
        
    )
    print(input_ids)
    print()
    print(attention_mask)

Generating train split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/32 [00:00<?, ? examples/s]

Map:   0%|          | 0/27 [00:00<?, ? examples/s]

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

[[     2  33501    603    671  14239    674  19306    476   6911 235269
   44600    675    671   3772    674   6572   4024   4807 235265  15615
     476   3590    674  47258  56382]]

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[[     2  33501    603    671  14239    674  19306    476   6911 235269
   44600    675    671   3772    674   6572   4024   4807 235265  15615
     476   3590    674  47258  56382]]

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[[     2  33501    603    671  14239    674  19306    476   6911 235269
   44600    675    671   3772    674   6572   4024   4807 235265  15615
     476   3590    674  47258  56382]]

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[[     2  33501    603    671  14239    674  19306    476   6911 235269
   44600    675    671   3772    674   6572   4024   4807 235265  15615
     476   3590    674  47258  56382]]

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[[     2  33501    603    671  14239    

In [70]:
def forward_and_loss_fn(params,
                        *,
                        model: transformer_lib.Transformer,
                        input_tokens: jax.Array,            # Shape [B, L]
                        input_mask: jax.Array,              # Shape [B, L]
                        positions: jax.Array,               # Shape [B, L]
                        attention_mask: jax.Array,          # [B, L, L]
                        ) -> jax.Array:
  """Forward pass and loss function.

  Args:
    params: model's input parameters.
    model: gemma transformer model to call.
    input_tokens: input tokens sequence, shape [B, L].
    input_mask: tokens to ignore when computing the loss, shape [B, L].
    positions: relative position of each token, shape [B, L].
    attention_mask: input attention mask, shape [B, L].

  Returns:
    Softmax cross-entropy loss for the next-token prediction task.
  """

  # Forward pass on the input data.
  # No attention cache is needed here.
  logits, _ = model.apply(
        params,
        input_tokens,
        positions,
        None,              # Attention cache is None.
        attention_mask,
    )

  # Exclude the last step as it does not appear in the targets.
  logits = logits[:, :-1]


  # Similarly, the first token cannot be predicteds.
  target_tokens = input_tokens[:, 1:]
  target_mask = input_mask[:, 1:]

  # Convert the target labels into one-hot encoded vectors.
  target_mask = target_mask[...,1:] # TODO
  one_hot = jax.nn.one_hot(target_tokens, logits.shape[-1])

  # Don't update on unwanted tokens.
  one_hot = one_hot * target_mask.astype(one_hot.dtype)[..., None]

  # Normalisation factor.
  norm_factor = 1 / (jnp.sum(target_mask) + 1e-8)

  # Return the nll loss.
  return -jnp.sum(jax.nn.log_softmax(logits) * one_hot) * norm_factor

The Gemma transformer requires an attention mask and position vector alongside each input. We can conveniently generate these using the following function:

In [71]:
def get_attention_mask_and_positions(example: jax.Array,
                                     pad_id : int,
                                     )-> tuple[jax.Array, jax.Array]:
  """Builds the position and attention mask vectors from the given tokens."""
  pad_mask = example != pad_id
  current_token_position = transformer_lib.build_positions_from_mask(pad_mask)
  attention_mask = transformer_lib.make_causal_attn_mask(pad_mask)
  return current_token_position, attention_mask

We can now build the train_step function which performs the backward pass and updates the model's parameters accordingly.

In [72]:
def train_step(model: transformer_lib.Transformer,
               params,
               optimizer: optax.GradientTransformation,
               opt_state: optax.OptState,
               pad_id: int,
               example):
  """Train step.

  Args:
    model: gemma transformer model.
    params: model's input parameters.
    optimizer: optax optimizer to use.
    opt_state: input optimizer's state.
    pad_id: id of the pad token.
    example: input batch.

  Returns:
    Training loss, updated parameters, updated optimizer state.
  """
  # Build the position and attention mask vectors.
  positions, attention_mask = get_attention_mask_and_positions(example['input_tokens'], pad_id)


  # Forward and backward passes
  train_loss, grads = jax.value_and_grad(forward_and_loss_fn)(params,
                                                             model=model,
                                                             input_tokens=example['input_tokens'],
                                                             input_mask=example['target_mask'],
                                                             positions=positions,
                                                             attention_mask=attention_mask)
  # Update the parameters
  updates, opt_state = optimizer.update(grads, opt_state)
  params = optax.apply_updates(params, updates)

  return train_loss, params, opt_state

Similarly, we build a `validation_step` function without backward pass.

And now the training loop itself.

In [73]:
@chex.dataclass(frozen=True)
class TrainingConfig:
  learning_rate: float
  num_epochs: int
  eval_every_n: int
  batch_size: int
  max_steps: int | None = None

from dataclasses import dataclass
import numpy as np


def train_loop(
    model: transformer_lib.Transformer,
    params,
    train_dataloader,
    tokenizer,
    training_cfg: TrainingConfig):


  compiled_train_step = jax.jit(train_step, static_argnames=['model', 'optimizer'])
  optimizer = optax.sgd(training_cfg.learning_rate)
  opt_state = optimizer.init(params)

  n_steps = 0
  avg_loss=0

  for i, train_example in enumerate(train_dataloader):
    train_loss, params, opt_state = train_step(model=model,
                                                        params=params,
                                                        optimizer=optimizer,
                                                        opt_state=opt_state,
                                                        pad_id=tokenizer.pad_token_id,
                                                        example=train_example)
    n_steps += 1
    avg_loss += train_loss
    print(f"train_loss {train_loss}")
    if training_cfg.max_steps is not None and n_steps > training_cfg.max_steps:
      break
  return params

We can fine-tune our model on a limited number of steps.

In [74]:
# Small seq size so that everything fits in memory
# SEQ_SIZE = 25
# tokenizer = GemmaTokenizer(vocab)
training_cfg = TrainingConfig(learning_rate=1e-4,
                              num_epochs=1,
                              eval_every_n=20,
                              batch_size=1,
                              max_steps=10)

params = train_loop(model=model_2b,
                    params={'params': params['transformer']},
                    train_dataloader=train_dataloader,
                    tokenizer=tokenizer,
                    training_cfg=training_cfg)

train_loss 3.4749553203582764
train_loss 3.1256206035614014
train_loss 2.8535666465759277
train_loss 2.6152141094207764
train_loss 2.44683837890625
train_loss 2.250701904296875
train_loss 2.087615966796875
train_loss 1.9332988262176514
train_loss 1.8218740224838257
train_loss 1.6936391592025757
train_loss 1.5728302001953125


Both the training loss and the validation's are going down. But is it working ? Let's try again with our previous example:

In [37]:
# sampler = sampler_lib.Sampler(
#     transformer=model_2b,
#     vocab=tokenizer,
#     params=params['params'],
# )

# sampler(
#     ["Translate this into French:\nHello, my name is Morgane.\n"],
#     total_generation_steps=30,
#     ).text